export enum EPostActions {
	POST_POST_STARTED = 'POST_POST_STARTED',
	POST_POST_SUCCEEDED = 'POST_POST_SUCCEEDED',
	POST_POST_FAILED = 'POST_POST_FAILED',

	GET_POSTS_STARTED = 'GET_POSTS_STARTED',
	GET_POSTS_SUCCEEDED = 'GET_POSTS_SUCCEEDED',
	GET_POSTS_FAILED = 'GET_POSTS_FAILED',

	GET_POST_STARTED = 'GET_POST_STARTED',
	GET_POST_SUCCEEDED = 'GET_POST_SUCCEEDED',
	GET_POST_FAILED = 'GET_POST_FAILED',

	PATCH_POST_STARTED = 'PATCH_POST_STARTED',
	PATCH_POST_SUCCEEDED = 'PATCH_POST_SUCCEEDED',
	PATCH_POST_FAILED = 'PATCH_POST_FAILED',

	DELETE_POST_STARTED = 'DELETE_POST_STARTED',
	DELETE_POST_SUCCEEDED = 'DELETE_POST_SUCCEEDED',
	DELETE_POST_FAILED = 'DELETE_POST_FAILED'
}
